-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.object_comment
(

    CONSTRAINT object_comment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.object_transfrom
(

    CONSTRAINT object_transfrom_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sensor_device
(

    CONSTRAINT sensor_device_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.station
(

    CONSTRAINT station_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.object_comment
    ADD CONSTRAINT fkop4a3kabrd7u1vlavfgjkoy8y FOREIGN KEY (object_transform_id)
    REFERENCES public.object_transfrom (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.object_transfrom
    ADD CONSTRAINT fk87n6y4yuhtayqaplcn43cl599 FOREIGN KEY (sensor_id)
    REFERENCES public.sensor_device (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.object_transfrom
    ADD CONSTRAINT fkta9o5pec1ptvt2mu0bxsvvk5n FOREIGN KEY (station_id)
    REFERENCES public.station (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sensor_device
    ADD CONSTRAINT fkhl3asgyccstwraqa2fs4ymnhw FOREIGN KEY (station_id)
    REFERENCES public.station (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;